name: CI

on:
  - push
  - workflow_call

env:
  GOEXPERIMENT: jsonv2

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version: 'stable'

      - run: go version

      - name: Go mod tidy
        run: go mod tidy

      - name: Go mod download
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run Go imports
        run: |-
          go install golang.org/x/tools/cmd/goimports@latest
          BAD_IMPORTS=$(goimports -local 'github.com/quetzyg' -l command config device httpclient ip meta shellygen1 shellygen2)
          if [ "$BAD_IMPORTS" != "" ]; then
            echo "Files with bad imports:"
            echo "$BAD_IMPORTS"
            exit 1
          fi

      - name: Go CI Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

      - name: Run tests
        run: |-
          GOEXPERIMENT=jsonv2 go test -race -shuffle=on -failfast -vet=off -v ./... -coverprofile=coverage.txt
          go tool cover -html=coverage.txt -o coverage.html

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
