name: Release

on:
  workflow_dispatch:
    branches: [master]

permissions:
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  release:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - run: go version

      - name: Build binaries
        id: build
        run: |-
          VERSION=$(date +'%g.%m.%d')-$(git rev-parse --short HEAD)
          TIME=$(date +'%T')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          GOOS=linux GOARCH=amd64 go build -v -ldflags "-X github.com/Stowify/IoTune.Version=$VERSION -X github.com/Stowify/IoTune.BuildTime=$TIME" -o iotune-linux ./cmd/iotune/main.go
          GOOS=darwin GOARCH=amd64 go build -v -ldflags "-X github.com/Stowify/IoTune.Version=$VERSION -X github.com/Stowify/IoTune.BuildTime=$TIME" -o iotune-macos ./cmd/iotune/main.go
          GOOS=windows GOARCH=amd64 go build -v -ldflags "-X github.com/Stowify/IoTune.Version=$VERSION -X github.com/Stowify/IoTune.BuildTime=$TIME" -o iotune-win.exe ./cmd/iotune/main.go

      - uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.build.outputs.version }}
          tag: ${{ steps.build.outputs.version }}
          artifacts: "iotune-*"
          token: ${{ secrets.GITHUB_TOKEN }}
